trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.0.100-preview9-014004'
    includePreviewVersions: true
- script: dotnet build
  displayName: 'Build'